### ISSUE TITLE
 ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by freezegr** [SocialBlade/socialblade-js#8]
```
(node:4508) UnhandledPromiseRejectionWarning: ReferenceError: fetch is not defined
    at Matrix.<anonymous> (C:\Users\xaris\desktop\follow\node_modules\socialblade\dist\matrix.js:29:13)
    at Generator.next (<anonymous>)
    at C:\Users\xaris\desktop\follow-sub\node_modules\socialblade\dist\matrix.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\xaris\desktop\follow\node_modules\socialblade\dist\matrix.js:4:12)
    at Matrix.request (C:\Users\xaris\desktop\follow\node_modules\socialblade\dist\matrix.js:25:16)
    at Matrix.<anonymous> (C:\Users\xaris\desktop\follow\node_modules\socialblade\dist\matrix.js:38:31)
    at Generator.next (<anonymous>)
    at C:\Users\xaris\desktop\follow\node_modules\socialblade\dist\matrix.js:8:71
    at new Promise (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
how to fix it

**Comment by timcole** [comment]
Node does not have fetch built-in in your browser, there are many different options you can use though.
As stated in the [README](https://github.com/SocialBlade/socialblade-js#install).
>Library does not force any fetch polyfills, If you don't already have a fetch polyfill we recommend using isomorphic-unfetch like the tests use.

**Comment by freezegr** [comment]
Thank you.
